rvm:
#  - 1.8.7
#  - 1.9.2
  - 1.9.3
#  - ree-1.8.7
before_script:
  - "mysql -e 'create database lokka_test;'"
  - "psql -c 'create database lokka_test;' -U postgres"
env:
  - DATABASE_URL="mysql://0.0.0.0/lokka_test"
  - DATABASE_URL="postgres://postgres@127.0.0.1/lokka_test"
  - DUMMY=DUMMY # sqlite
notifications:
  irc: "assam.udcp.info:36666#udcp-dev"
branches:
  only:
    - master
    - lokka
